language: generic

sudo: required
service:
  - docker

before_install:
  - docker build -t Bjornhona/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Bjornhona/docker-react npm run test